### ISSUE TITLE
questions about the remote module imports

### ISSUE THREAD

**Issue by junxiongchu** [module-federation/webpack-4#10]
[https://stackblitz.com/github/wpmjs/examples/tree/main/webpack4-module-federation/webpack4-vue-cli-umi-react?file=vue-cli-host%2Fsrc%2FApp.vue](url)

import UmiApp from 'umi/App'
import {applyReactInVue} from "vuereact-combined"
import VueCliRemote from "vueCliRemote/App"

export default {
  name: 'App',
  components: {
    UmiApp: applyReactInVue(UmiApp),
    VueCliRemote
    // Button,
  }
}

in this example, vue-cli-host were able to import VueCliRemote from "vueCliRemote/App"  and use VueCliRemote as  vue component directly, but when i import demo from 'demo/App'  and console log the demo at main.js, the result is undefined. when i async console log the result is ok.

eg:   main.js:

import ElementUI from 'element-ui'
import Vue from 'vue'
import demo from 'demo/App'

import App from './App.vue'

Vue.config.productionTip = false
Vue.use(ElementUI, { size: 'medium' })

console.log(demo)  //  undefined
console.log(window.demo) // undefined

setTimeout(() => { 
   console.log(window.demo)  //   is ok 
 }, 5000)

new Vue({
  render: h => h(App),
}).$mount('#app')

so how to get timely and accurate results from normal  "import  xxx from 'xxxx/xxx' " about the remote module ?

**Comment by zhangHongEn** [comment]
need to complete [bootstrap](https://webpack.js.org/concepts/module-federation/#troubleshooting), I will find time to fix this check, it will throw an error saying that bootstrap needs to be completed

**Comment by zhangHongEn** [comment]
![image](https://github.com/module-federation/webpack-4/assets/26006485/baed47df-4c23-48b6-8776-1a101ac240a5)

bootstrap check completed, mf-webpack4@1.4.2
