### ISSUE TITLE
shared: ['vue']报错

### ISSUE THREAD

**Issue by 1259549061** [module-federation/webpack-4#12]
请问一下 我跟着文档写的 加了shared: ["vue"],之后会报错，不加不报错
chain.plugin("moduleFederation")
      .use(MF, [{
        name: "vueCliRemote",
        shared: ["vue"],
        exposes: {
          "./App": "src/App.vue"
        }
      }])

![b32198e04f9f99b0ab8d437e7bf04e6](https://github.com/module-federation/webpack-4/assets/28998743/aa055c0a-731c-47b2-b43e-ded00ac5beb4)

**Comment by zhangHongEn** [comment]
正常使用没有报错
![image](https://github.com/module-federation/webpack-4/assets/26006485/da9d34e0-632c-49dd-b49f-16c58c60461b)

发一下报错代码吧
index.js:15
App.vue:23

**Comment by 1259549061** [comment]
> 
![ed070fad5c160b9dfc2556faa64de58](https://github.com/module-federation/webpack-4/assets/28998743/48523658-fb18-4fc0-b027-60a188d19abd)

![7963011e6f9bd277ab68829e72d2955](https://github.com/module-federation/webpack-4/assets/28998743/daaa5a51-40f7-40a5-b6c0-ee9cf003a90f)

**Comment by zhangHongEn** [comment]
表现确实不符预期, 能否提供一个可复现例子

**Comment by 1259549061** [comment]
> 表现确实不符预期, 能否提供一个可复现例子

好的，可能是我这边引入了qiankun引起的，我最近得空弄个例子

**Comment by 1259549061** [comment]
> 目前未定位到问题, 如果是qiankun可以参考这个[issue](https://github.com/module-federation/webpack-4/issues/7)中的demo
整理了个demo，shared放开也会报错，但是和上次的报错看上去不一样
https://gitee.com/ljjf/qiankun-mf-demo.git

![e32ec565ca0d6ae02a640c06eee9b00](https://github.com/module-federation/webpack-4/assets/28998743/d5655442-5413-468b-9036-ccf3d6c1fa2e)

**Comment by 1259549061** [comment]
> 

我这边这样改了还是不行

**Comment by 1259549061** [comment]
> 看报错的文档链接, 不可以在main.js里面引入shared模块vue 需要在view-micro这么做:
> 
> 1. 修改 main.js 文件名为 bootstrap.js
> 2. 新建 main.js 代码内容为
> 
> ```js
> import("./bootstrap")
> ```
@zhangHongEn  我这边这样改了还是不行

**Comment by zhangHongEn** [comment]
> 看报错的文档链接, 不可以在main.js里面引入shared模块vue 需要在view-micro这么做:
> 
> 1. 修改 main.js 文件名为 bootstrap.js
> 2. 新建 main.js 代码内容为
> 
> ```js
> import("./bootstrap")
> ```

是否可以, 我使用你的demo增加bootstrap步骤后是可以的
![image](https://github.com/module-federation/webpack-4/assets/26006485/bf8a23c3-dcd6-4bbb-8201-43718f2421ed)

**Comment by 1259549061** [comment]
> > 看报错的文档链接, 不可以在main.js里面引入shared模块vue 需要在view-micro这么做:
> > 
> > 1. 修改 main.js 文件名为 bootstrap.js
> > 2. 新建 main.js 代码内容为
> > 
> > ```js
> > import("./bootstrap")
> > ```
> 
> 是否可以, 我使用你的demo增加bootstrap步骤后是可以的 ![image](https://user-images.githubusercontent.com/26006485/248710894-bf8a23c3-dcd6-4bbb-8201-43718f2421ed.png)

嗯，我试了下可以了  ，感谢~
