### ISSUE TITLE
remoteEntry.js use hashes?

### ISSUE THREAD

**Issue by junxiongchu** [module-federation/webpack-4#13]
take advantage of browser caching，like remoteEntry.[chunkhash].js

**Comment by zhangHongEn** [comment]
like index.html, remoteEntry as a fixed entry point of an independent module does not need hash

**Comment by junxiongchu** [comment]
well, my project uses a meta data json file for load remoteEntry js, this json file contains the file name mapping of the remoteEntry file, the remoteEntry file name is dynamic, only update when content changes, like webpack chunkhash.

because the remoteEntry file size may be too large, so i want to use the characteristics of browser caching to speed up the display of pages.

but the hash I generated with the webpack compilation.hash,  you know the compilation.hash is unstable, so it would be nice  if your plugin can use like stable chunkhash.
