### ISSUE TITLE
无法加载远程子应用

### ISSUE THREAD

**Issue by kf53916** [module-federation/webpack-4#15]
您好，无法加载远程子应用，报错如下：
![image](https://github.com/module-federation/webpack-4/assets/4316878/c018194c-dfeb-4849-960d-8d08be9eaa12)
可能是什么原因，按照demo配置的

**Comment by kf53916** [comment]
远程应用的配置：
![image](https://github.com/module-federation/webpack-4/assets/4316878/ebf5df50-618f-44c9-ada8-3a955bd85c35)
本地应用的配置：
![image](https://github.com/module-federation/webpack-4/assets/4316878/ab1a1c3f-8ad9-499f-9d45-3a1364b5e32b)
![image](https://github.com/module-federation/webpack-4/assets/4316878/d3568827-9f55-4beb-8758-383e55be6628)

**Comment by zhangHongEn** [comment]
components拼错了，hcc 组件注册失败

**Comment by kf53916** [comment]
非常感谢，确实是拼写错误，demo可以正常使用远程组件，但是集成到项目里面，远程应用出现如下错误：
![image](https://github.com/module-federation/webpack-4/assets/4316878/075fb87e-c3ba-4c4d-a8c6-a73681ea1aa3)
配置和demo里面的一样

**Comment by zhangHongEn** [comment]
是webpack还是vue-cli, 能否提供host与remote的webpack配置

**Comment by zhangHongEn** [comment]
也可以把可复现项目发我邮箱，我来排查 
zhang_h_n@163.com
