### ISSUE TITLE
Getting unexpected errors while running the app with MF Plugin

### ISSUE THREAD

**Issue by kshitijtalwar23** [module-federation/webpack-4#2]
**Error Stack Trace-** 

ERROR in ./$_mfplugin_virtualExposes/index.js
eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\$_mfplugin_virtualExposes'
 @ ./$_mfplugin_virtualExposes/index.js 2:4-77 6:0-73

ERROR in (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true
eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\node_modules\webpack-dev-server\client'
 @ (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true 2:4-77
 @ multi (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true (webpack)/hot/dev-server.js ./src/index.js

ERROR in (webpack)/hot/dev-server.js
eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\node_modules\webpack\hot'
 @ (webpack)/hot/dev-server.js 2:4-77
 @ multi (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true (webpack)/hot/dev-server.js ./src/index.js

ERROR in ./src/index.js
eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\src'
 @ ./src/index.js 2:4-77

ERROR in ./$_mfplugin_virtualExposes/index.js
eact-webpack4-mf$_mfplugin_virtualSetSharedindex.js' in 'C:\dev\react-webpack4-mf\$_mfplugin_virtualExposes'
 @ ./$_mfplugin_virtualExposes/index.js 9:4-76
 
 **webpack config**
 const HtmlWebpackPlugin = require("html-webpack-plugin");
const ReactRefreshPlugin = require("@pmmmwh/react-refresh-webpack-plugin")
const path = require("path")
const MF = require("mf-webpack4")
module.exports = {
  entry: "./src/index.js",
  context: __dirname,
  resolve: {
    extensions: [".js", ".json", ".jsx", ".css"],
  },
  output: {
    filename: '[name].js',
    chunkFilename: "[name].js",
    path: `${__dirname}/dist`,
    publicPath: "http://localhost:9001/",
  },
  devServer: {
    hot: true,
    open: false,
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
    allowedHosts: 'all',
    historyApiFallback: true,
    port: 9001,
  },
  plugins: [
    new ReactRefreshPlugin({
      overlay: false
    }),
    new MF({
      name: "app1",
      filename: "remoteEntry.js",
      shared: {
        "react": {
          singleton: true,
        },
        "react-dom": {
          singleton: false,
        }
      },
      exposes: {
        "./App": "./src/App"
      }
    }),
    new HtmlWebpackPlugin()
  ],
  module: {
    rules: [
      {
        test: /\.m?jsx?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              configFile: path.resolve(process.cwd(), "babel.config.js"),
              babelrc: false
            }
          }
        ]
      },
    ]
  }
};

**Comment by zhangHongEn** [comment]
> **Error Stack Trace-**
> 
> ERROR in ./$_mfplugin_virtualExposes/index.js eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf$_mfplugin_virtualExposes' @ ./$_mfplugin_virtualExposes/index.js 2:4-77 6:0-73
> 
> ERROR in (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\node_modules\webpack-dev-server\client' @ (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true 2:4-77 @ multi (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true (webpack)/hot/dev-server.js ./src/index.js
> 
> ERROR in (webpack)/hot/dev-server.js eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\node_modules\webpack\hot' @ (webpack)/hot/dev-server.js 2:4-77 @ multi (webpack)-dev-server/client?protocol=ws%3A&hostname=0.0.0.0&port=9001&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true (webpack)/hot/dev-server.js ./src/index.js
> 
> ERROR in ./src/index.js eact-webpack4-mf$_mfplugin_virtualInitConfigindex.js' in 'C:\dev\react-webpack4-mf\src' @ ./src/index.js 2:4-77
> 
> ERROR in ./$_mfplugin_virtualExposes/index.js eact-webpack4-mf$_mfplugin_virtualSetSharedindex.js' in 'C:\dev\react-webpack4-mf$_mfplugin_virtualExposes' @ ./$_mfplugin_virtualExposes/index.js 9:4-76
> 
> **webpack config** const HtmlWebpackPlugin = require("html-webpack-plugin"); const ReactRefreshPlugin = require("@pmmmwh/react-refresh-webpack-plugin") const path = require("path") const MF = require("mf-webpack4") module.exports = { entry: "./src/index.js", context: __dirname, resolve: { extensions: [".js", ".json", ".jsx", ".css"], }, output: { filename: '[name].js', chunkFilename: "[name].js", path: `${__dirname}/dist`, publicPath: "http://localhost:9001/", }, devServer: { hot: true, open: false, headers: { 'Access-Control-Allow-Origin': '*', }, allowedHosts: 'all', historyApiFallback: true, port: 9001, }, plugins: [ new ReactRefreshPlugin({ overlay: false }), new MF({ name: "app1", filename: "remoteEntry.js", shared: { "react": { singleton: true, }, "react-dom": { singleton: false, } }, exposes: { "./App": "./src/App" } }), new HtmlWebpackPlugin() ], module: { rules: [ { test: /.m?jsx?$/, exclude: /node_modules/, use: [ { loader: 'babel-loader', options: { configFile: path.resolve(process.cwd(), "babel.config.js"), babelrc: false } } ] }, ] } };

Fixed the problem of forgetting to handle the Windows path. You can use the new version

npm i mf-webpack@latest (released) or

npm i @module-federation/ webpack-4@1.0.1 (Not released yet)

**Comment by entranced** [comment]
What is the fix for this? I'm getting this error on Windows. The latest and only version on npmjs is 1.0.0.
