### ISSUE TITLE
can suport vue-cli + vue-cli ?

### ISSUE THREAD

**Issue by fengyux** [module-federation/webpack-4#5]
Uncaught (in promise) Error: not container
    at eval (VM4300 index.js:2:860)
    at p (VM4300 index.js:2:11947)
    at Generator.eval [as _invoke] (VM4300 index.js:2:11700)
    at Generator.eval [as next] (VM4300 index.js:2:12310)
    at e (VM4300 index.js:2:9285)
    at u (VM4300 index.js:2:9496)

app1 webpack config:
const MF = require("mf-webpack4")

module.exports = {
  configureWebpack: {
    entry: "./src/main.js",
    // output: {
    //   publicPath: ""
    // },
    devServer: {
      port: "9004"
    },
    plugins: [
      new MF({
        name: "app1",
        exposes: {
          "./App": "./src/App"
        },
        filename: 'remoteEntry.js',
      })
    ]
  }
}'

app2 webpack config:
const MF = require("mf-webpack4")

module.exports = {
  configureWebpack: {
    entry: "./src/main.js",
    // output: {
    //   publicPath: ""
    // },
    devServer: {
      port: "9004"
    },
    plugins: [
      new MF({
        name: "app2",
        remotes: {
          "app1": "app1@http://localhost:9005/js/remoteEntry.js",
          "promiseRemote": `promise {
            init() {},
            get() {
              return function () {
                return {
                  promiseRemote: "aaaa"
                }
              }
            }
          }`
        }
      })
    ]
  }
}

**Comment by zhangHongEn** [comment]
Modify the app1 port to 9005

**Comment by fengyux** [comment]
Modify the app1 port to 9005,stil have error

VM5631 index.js:2 Uncaught (in promise) Error: not container
    at eval (VM5631 index.js:2:860)
    at p (VM5631 index.js:2:11947)
    at Generator.eval [as _invoke] (VM5631 index.js:2:11700)
    at Generator.eval [as next] (VM5631 index.js:2:12310)
    at e (VM5631 index.js:2:9285)
    at u (VM5631 index.js:2:9496)

I print "console.log(window.app1)" ,get undefined;

**Comment by zhangHongEn** [comment]
I'll see tomorrow. If it is not compatible with vue-cli, I should be able to reproduce it easily

**Comment by fengyux** [comment]
Thank you every much!  It would be better if there was an online example

**Comment by zhangHongEn** [comment]
yes

**Comment by zhangHongEn** [comment]
finished

1. [vue-cli-matters-needing-attention](https://github.com/module-federation/webpack-4#vue-cli-matters-needing-attention)
2. [online example](https://stackblitz.com/github/wpmjs/examples/tree/main/webpack4-module-federation/webpack4-vue-cli-umi-react)

**Comment by fengyux** [comment]
Thanks for your work

**Comment by fengyux** [comment]
mf-webpack4 and @originjs/vite-plugin-federation whether interoperability can be achieved

**Comment by zhangHongEn** [comment]
> mf-webpack4 和@originjs/vite-plugin-federation 是否可以实现互操作

It should be possible, different mf modules only communicate through init() and get() of window[global], the probability of being unable to cooperate with each other and conflicting is very small
