### ISSUE TITLE
资源加载不到吗

### ISSUE THREAD

**Issue by 1259549061** [module-federation/webpack-4#9]
app1：
chainWebpack: config => {
    config.optimization.splitChunks().clear();
        config.plugin("moduleFederation")
            .use(MF, [{
                name: "lib_remote",
                shared: ["vue"],
                exposes: {
                    "./ClaimsQuestion": "src/components/ClaimsQuestion/ClaimsQuestion.vue",
                    "./DiyPopup": "src/components/commonPopup/DiyPopup.vue",
                    "./HistroyBack": "src/components/commonPopup/HistroyBack.vue",
                    "./Layout": "src/components/layout/layout.vue",
                }
            }])
}

app2：
chainWebpack: config => {
    config.optimization.splitChunks().clear();
        config.plugin("moduleFederation")
            .use(MF, [{
                name: "vue-micro-app",
                remotes: {
                    "lib_remote": "lib_remote@http://192.168.5.51:3000/js/remoteEntry.js"
                }
            }])
}

启动后报错了
![1683878015042](https://github.com/module-federation/webpack-4/assets/28998743/8423108c-2fc0-4ec5-a937-02409cf68a6f)

请问这个怎么回事

**Comment by zhangHongEn** [comment]
<img width="968" alt="image" src="https://github.com/module-federation/webpack-4/assets/26006485/1b49055a-432d-42aa-a5d2-5b6512191abc">
需要设置app2的publicPath, 看一下发出的网络请求这个url的地址是什么

**Comment by zhangHongEn** [comment]
<img width="831" alt="image" src="https://github.com/module-federation/webpack-4/assets/26006485/b014b57c-1948-4573-a441-acb4d6b800de">
app2设置publicPath把端口设置为3000

**Comment by 1259549061** [comment]
> publicPath

ok，谢谢，是这个问题
